name: ML CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  train-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Preprocessing
      run: python src/preprocess.py

    - name: Train Model
      run: python src/train.py

    - name: Evaluate Model
      run: python src/evaluate.py

    - name: Run Unit Tests
      run: pytest test_model.py

    - name: Build Docker Image
      run: docker build -t ml-api .

    - name: Simulated Deployment
      run: echo "Deploying model..."
